### ISSUE TITLE
Rear Headset/Line Out port not working.

### ISSUE THREAD

**Issue by mmfixemer** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#12] opened 2021-03-13 16:45 UTC
Hi,
i wanted to use the rear Headset port or line out but it didn't work, it just played through the internal speaker. Front Headset port is working fine. Just need to unplug it and replug it if i booted the Mac with it plugged in. I guess its a Kext issue with the motherboard combination. Let me kNow if you have any solution for it. also still persists with lates OpenCore update you provided. Let me know if u need any more details like logs or anything.

Best regards Mike

**Comment by varszegimarcell** [comment] 2021-03-14 18:14
Hey!

Do you use the 3020SFF, the 3020MT, or the 3020M variant? 

You may need to change to a different AppleALC layout-id.

**Comment by mmfixemer** [comment] 2021-03-15 06:35
I'm using the SSF version

**Comment by varszegimarcell** [comment] 2021-03-19 10:38
I will test it out this afternoon. 

I originally used layout-id 3, but with that, the internal speaker wasn't working. With layout-id 16, the speaker and front jack works, but I actually never used the rear one :D

**Comment by varszegimarcell** [comment] 2021-03-22 13:42
Well, the rear jack do not work for me either. :D Thanks for letting me know! I'll try to fix this issue in the next update, it is most likely configuration related in my config.plist. I suspect that we have to use a different AppleALC layout-id. I try to be as fast as possible, but due to my university studies, I am quite busy, and I do not have too much free time.

**Comment by mmfixemer** [comment] 2021-03-22 14:26
Alright I thought so hehe. And don't worry it's not so important. Focused on your studies that's more important bro. I can live with using the front port for now.

**Comment by varszegimarcell** [comment] 2021-03-23 20:17
Hey!

I have investigated the issue, and now I'm happy to tell you that the issue is fixed. Check out the latest release. I had to change the audio layout to 17. Now both front and rear jacks are working, although I had no 3,5mm input jack devices to test the line ins. 

Can you please try it out? Leave a feedback if the issue is still persist or not, so I can close this issue.

Cheers
M

**Comment by mmfixemer** [comment] 2021-03-24 16:01
Hey,
keeping it short rear audio worked but having issues with audio lagging and stuttering after the update of the config file.
i had the same issue before and i reformated my pc. i dont know if im doing something wrong in updating the config file. maybe you could make a small guide on how to update the config without changing for example the smbios.
i will attach 2 videos so you can see and hear what i mean
[After Updating Config File](https://youtu.be/-tWIDls5n5g)
[After Going back to old config ](https://youtu.be/Xw3314JeMVc)

**Comment by varszegimarcell** [comment] 2021-03-24 21:00
Hi

I don't know why this happens, I've tested it on my system and it works flawlessly for me. Can you delete your entire EFI and restart from scratch? It is pretty weird, and I don't know any reasons why would this happen. All 3020SFF computers use the same Realtek AC3220 audio interface. 

I strongly recommend you to save your SMBIOS values in a separate file, so you can just copy paste it back when it needed. Saving the values MLB, SystemSerialNumber, SystemUUID is a must, and I would back up the ROM value for convenience too. I keep for example a backup of my entire older, well working EFI folders on Google Drive, and have these values in the config.plist, and in an another text file too. You have to be especially careful with these serials if you made iMessage working, because these serials make able to use all Apple services even in the case of full reinstall. It will be impossible to make these services working again with different serials, as the ROM value (which is the MAC address of your network card) is pretty much permanent. Once you have serial records in Apple's databases with a given MAC address, you are basically linked to those serials, and you cannot replace them. So yes, I know it is a pain to copy paste every time these serials, but I have no better method for this either. Hackintoshing is a fiddly process sadly. :/

**Comment by mmfixemer** [comment] 2021-03-25 16:22
Hi,
thanks for you help, i maybe want to learn more about opencore and hackintosh and if your ok i can maybe also contribute if i learned a bit more. i will try your suggestion and i will report back and maybe make a tutorial for other people to follow if i get it working.

**Comment by mmfixemer** [comment] 2021-03-27 04:57
Hey,
i started with the new EFI and transferred my serials over and it worked no more line out issue, i still have to check my microphone but i guess its my mic is busted and not the input ports. I will keep you updated and in case it is an issue i will open a new Issue

**Closed** 2021-05-20 06:52 UTC
Labels: bug
